//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountsReceivable> AccountsReceivables { get; set; }
        public DbSet<AdditionalProduct> AdditionalProducts { get; set; }
        public DbSet<AgeRanx> AgeRanges { get; set; }
        public DbSet<BatchEvent> BatchEvents { get; set; }
        public DbSet<BidderQuoteDetail> BidderQuoteDetails { get; set; }
        public DbSet<BidderQuote> BidderQuotes { get; set; }
        public DbSet<BudgetedYard> BudgetedYards { get; set; }
        public DbSet<cnfc> cnfcs { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyBidStatus> CompanyBidStatuses { get; set; }
        public DbSet<CompanyOrderStatus> CompanyOrderStatuses { get; set; }
        public DbSet<CompanyProjectProductStatus> CompanyProjectProductStatuses { get; set; }
        public DbSet<CompanyProjectStatus> CompanyProjectStatuses { get; set; }
        public DbSet<CompanyQuoteStatus> CompanyQuoteStatuses { get; set; }
        public DbSet<CompanyUser> CompanyUsers { get; set; }
        public DbSet<CompetitorPlant> CompetitorPlants { get; set; }
        public DbSet<Competitor> Competitors { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<ContactNote> ContactNotes { get; set; }
        public DbSet<CreditStatus> CreditStatuses { get; set; }
        public DbSet<CustomerEvent> CustomerEvents { get; set; }
        public DbSet<CustomerEventType> CustomerEventTypes { get; set; }
        public DbSet<CustomerType> CustomerTypes { get; set; }
        public DbSet<DeletedItem> DeletedItems { get; set; }
        public DbSet<DeviationType> DeviationTypes { get; set; }
        public DbSet<Division> Divisions { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<ErrorLog> ErrorLogs { get; set; }
        public DbSet<EventFrequency> EventFrequencies { get; set; }
        public DbSet<EventStatu> EventStatus { get; set; }
        public DbSet<FieldConfig> FieldConfigs { get; set; }
        public DbSet<LinesOfBusiness> LinesOfBusiness { get; set; }
        public DbSet<Locations_Divisions_Lookup> Locations_Divisions_Lookup { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<LostReason> LostReasons { get; set; }
        public DbSet<ManagersSalesman> ManagersSalesmen { get; set; }
        public DbSet<OracleExport> OracleExports { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<PaymentTerm> PaymentTerms { get; set; }
        public DbSet<Plant> Plants { get; set; }
        public DbSet<PlantLinesOfBusiness> PlantLinesOfBusiness { get; set; }
        public DbSet<PlantProductPrice> PlantProductPrices { get; set; }
        public DbSet<PlantProduct> PlantProducts { get; set; }
        public DbSet<PourSchedule> PourSchedules { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductLineLineOfBusiness> ProductLineLineOfBusinesses { get; set; }
        public DbSet<ProductLine> ProductLines { get; set; }
        public DbSet<ProductTemplate> ProductTemplates { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<ProductUsage> ProductUsages { get; set; }
        public DbSet<ProjectBidderCharge> ProjectBidderCharges { get; set; }
        public DbSet<ProjectBidderNote> ProjectBidderNotes { get; set; }
        public DbSet<ProjectBidderProduct> ProjectBidderProducts { get; set; }
        public DbSet<ProjectBidder> ProjectBidders { get; set; }
        public DbSet<ProjectBidderStatus> ProjectBidderStatuses { get; set; }
        public DbSet<ProjectCharge> ProjectCharges { get; set; }
        public DbSet<ProjectChargeType> ProjectChargeTypes { get; set; }
        public DbSet<ProjectDistance> ProjectDistances { get; set; }
        public DbSet<ProjectHistorySummary> ProjectHistorySummaries { get; set; }
        public DbSet<ProjectMapQtyRange> ProjectMapQtyRanges { get; set; }
        public DbSet<ProjectNote> ProjectNotes { get; set; }
        public DbSet<ProjectProduct> ProjectProducts { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectType> ProjectTypes { get; set; }
        public DbSet<ProspectNote> ProspectNotes { get; set; }
        public DbSet<ProspectQuantity> ProspectQuantities { get; set; }
        public DbSet<ProspectRegion> ProspectRegions { get; set; }
        public DbSet<Prospect> Prospects { get; set; }
        public DbSet<PSI> PSIs { get; set; }
        public DbSet<QuoteDetail> QuoteDetails { get; set; }
        public DbSet<QuoteGuid> QuoteGuids { get; set; }
        public DbSet<Quote> Quotes { get; set; }
        public DbSet<QuoteSection> QuoteSections { get; set; }
        public DbSet<QuoteStandardClaus> QuoteStandardClauses { get; set; }
        public DbSet<QuoteStatus> QuoteStatuses { get; set; }
        public DbSet<QuoteSurcharge> QuoteSurcharges { get; set; }
        public DbSet<QuoteType> QuoteTypes { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SalespersonContact> SalespersonContacts { get; set; }
        public DbSet<SalesPersonRegion> SalesPersonRegions { get; set; }
        public DbSet<ScheduleDetail> ScheduleDetails { get; set; }
        public DbSet<ScheduleItem> ScheduleItems { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<Source> Sources { get; set; }
        public DbSet<SourceSystem> SourceSystems { get; set; }
        public DbSet<StandardClaus> StandardClauses { get; set; }
        public DbSet<Status> Statuses { get; set; }
        public DbSet<Surcharge> Surcharges { get; set; }
        public DbSet<TemplatedProduct> TemplatedProducts { get; set; }
        public DbSet<TemplatedProductType> TemplatedProductTypes { get; set; }
        public DbSet<Terms_Discount> Terms_Discount { get; set; }
        public DbSet<TimeCalendar> TimeCalendars { get; set; }
        public DbSet<TQS_bbty> TQS_bbty { get; set; }
        public DbSet<TQS_chlc> TQS_chlc { get; set; }
        public DbSet<TQS_cnfc> TQS_cnfc { get; set; }
        public DbSet<TQS_encd> TQS_encd { get; set; }
        public DbSet<TQS_envr> TQS_envr { get; set; }
        public DbSet<TQS_mtac> TQS_mtac { get; set; }
        public DbSet<TQS_mtbt> TQS_mtbt { get; set; }
        public DbSet<TQS_mtlc> TQS_mtlc { get; set; }
        public DbSet<TQS_mtlp> TQS_mtlp { get; set; }
        public DbSet<TQS_mxca> TQS_mxca { get; set; }
        public DbSet<TQS_mxcc> TQS_mxcc { get; set; }
        public DbSet<TQS_prjp> TQS_prjp { get; set; }
        public DbSet<TQS_work> TQS_work { get; set; }
        public DbSet<Unit_Of_Measure> Unit_Of_Measure { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<usersDivision> usersDivisions { get; set; }
        public DbSet<ValueAdd> ValueAdds { get; set; }
        public DbSet<VehicleType> VehicleTypes { get; set; }
        public DbSet<ZoneCode> ZoneCodes { get; set; }
        public DbSet<consumersprojectimport> consumersprojectimports { get; set; }
        public DbSet<BI_Results> BI_Results { get; set; }
        public DbSet<BI_Exports> BI_Exports { get; set; }
    }
}
