//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBidStatus
    {
        public CompanyBidStatus()
        {
            this.ProjectBidderProducts = new HashSet<ProjectBidderProduct>();
            this.ProjectProducts = new HashSet<ProjectProduct>();
            this.Projects = new HashSet<Project>();
        }
    
        public int CompanyBidStatusID { get; set; }
        public string CompanyBidStatusName { get; set; }
        public int CompanyID { get; set; }
        public string SystemCode { get; set; }
        public Nullable<int> MSStatusID { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<ProjectBidderProduct> ProjectBidderProducts { get; set; }
        public virtual ICollection<ProjectProduct> ProjectProducts { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
