//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.AccountsReceivables = new HashSet<AccountsReceivable>();
            this.AdditionalProducts = new HashSet<AdditionalProduct>();
            this.AgeRanges = new HashSet<AgeRanx>();
            this.BatchEvents = new HashSet<BatchEvent>();
            this.CompanyBidStatuses = new HashSet<CompanyBidStatus>();
            this.CompanyOrderStatuses = new HashSet<CompanyOrderStatus>();
            this.CompanyProjectProductStatuses = new HashSet<CompanyProjectProductStatus>();
            this.CompanyProjectStatuses = new HashSet<CompanyProjectStatus>();
            this.CompanyQuoteStatuses = new HashSet<CompanyQuoteStatus>();
            this.CompanyUsers = new HashSet<CompanyUser>();
            this.Competitors = new HashSet<Competitor>();
            this.CreditStatuses = new HashSet<CreditStatus>();
            this.CustomerEventTypes = new HashSet<CustomerEventType>();
            this.CustomerTypes = new HashSet<CustomerType>();
            this.Divisions = new HashSet<Division>();
            this.Employees = new HashSet<Employee>();
            this.ErrorLogs = new HashSet<ErrorLog>();
            this.EventFrequencies = new HashSet<EventFrequency>();
            this.FieldConfigs = new HashSet<FieldConfig>();
            this.LinesOfBusinesses = new HashSet<LinesOfBusiness>();
            this.LostReasons = new HashSet<LostReason>();
            this.OracleExports = new HashSet<OracleExport>();
            this.Orders = new HashSet<Order>();
            this.PaymentTerms = new HashSet<PaymentTerm>();
            this.Products = new HashSet<Product>();
            this.ProductLines = new HashSet<ProductLine>();
            this.ProductUsages = new HashSet<ProductUsage>();
            this.ProjectCharges = new HashSet<ProjectCharge>();
            this.ProjectMapQtyRanges = new HashSet<ProjectMapQtyRange>();
            this.Projects = new HashSet<Project>();
            this.ProjectTypes = new HashSet<ProjectType>();
            this.Prospects = new HashSet<Prospect>();
            this.ProductTypes = new HashSet<ProductType>();
            this.QuoteTypes = new HashSet<QuoteType>();
            this.Sources = new HashSet<Source>();
            this.StandardClauses = new HashSet<StandardClaus>();
            this.Surcharges = new HashSet<Surcharge>();
            this.Terms_Discount = new HashSet<Terms_Discount>();
            this.TQS_bbty = new HashSet<TQS_bbty>();
            this.TQS_encd = new HashSet<TQS_encd>();
            this.TQS_envr = new HashSet<TQS_envr>();
            this.TQS_mtac = new HashSet<TQS_mtac>();
            this.TQS_mtbt = new HashSet<TQS_mtbt>();
            this.TQS_mtlc = new HashSet<TQS_mtlc>();
            this.TQS_mtlp = new HashSet<TQS_mtlp>();
            this.TQS_mxca = new HashSet<TQS_mxca>();
            this.TQS_mxcc = new HashSet<TQS_mxcc>();
            this.TQS_prjp = new HashSet<TQS_prjp>();
            this.TQS_work = new HashSet<TQS_work>();
            this.Unit_Of_Measure1 = new HashSet<Unit_Of_Measure>();
            this.Users = new HashSet<User>();
            this.VehicleTypes = new HashSet<VehicleType>();
            this.ZoneCodes = new HashSet<ZoneCode>();
            this.BI_Exports = new HashSet<BI_Exports>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string ST { get; set; }
        public string Zip { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string ServiceUrl { get; set; }
        public byte[] QuoteImage { get; set; }
        public int SourceSystemID { get; set; }
        public string CompanyCode { get; set; }
        public string ChannelID { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public Nullable<bool> UsesCategories { get; set; }
        public int MaxQuantity { get; set; }
        public int DefaultUomID { get; set; }
        public string Cert509 { get; set; }
        public bool UsesSAML { get; set; }
        public string TimeoutRedirect { get; set; }
        public bool ChangeProjectCode { get; set; }
        public bool UsesPriceIntegration { get; set; }
        public bool UsesSalesOrders { get; set; }
        public string Country { get; set; }
        public bool DeliverToExport { get; set; }
        public System.DateTime MsModificationDate { get; set; }
        public Nullable<int> DefaultQuoteTypeID { get; set; }
        public bool UseMultipleEscalators { get; set; }
        public int DefaultFirmUntilDays { get; set; }
        public bool AlwaysExportLatLngAddress { get; set; }
    
        public virtual ICollection<AccountsReceivable> AccountsReceivables { get; set; }
        public virtual ICollection<AdditionalProduct> AdditionalProducts { get; set; }
        public virtual ICollection<AgeRanx> AgeRanges { get; set; }
        public virtual ICollection<BatchEvent> BatchEvents { get; set; }
        public virtual QuoteType QuoteType { get; set; }
        public virtual SourceSystem SourceSystem { get; set; }
        public virtual Unit_Of_Measure Unit_Of_Measure { get; set; }
        public virtual ICollection<CompanyBidStatus> CompanyBidStatuses { get; set; }
        public virtual ICollection<CompanyOrderStatus> CompanyOrderStatuses { get; set; }
        public virtual ICollection<CompanyProjectProductStatus> CompanyProjectProductStatuses { get; set; }
        public virtual ICollection<CompanyProjectStatus> CompanyProjectStatuses { get; set; }
        public virtual ICollection<CompanyQuoteStatus> CompanyQuoteStatuses { get; set; }
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
        public virtual ICollection<Competitor> Competitors { get; set; }
        public virtual ICollection<CreditStatus> CreditStatuses { get; set; }
        public virtual ICollection<CustomerEventType> CustomerEventTypes { get; set; }
        public virtual ICollection<CustomerType> CustomerTypes { get; set; }
        public virtual ICollection<Division> Divisions { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<ErrorLog> ErrorLogs { get; set; }
        public virtual ICollection<EventFrequency> EventFrequencies { get; set; }
        public virtual ICollection<FieldConfig> FieldConfigs { get; set; }
        public virtual ICollection<LinesOfBusiness> LinesOfBusinesses { get; set; }
        public virtual ICollection<LostReason> LostReasons { get; set; }
        public virtual ICollection<OracleExport> OracleExports { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<PaymentTerm> PaymentTerms { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ProductLine> ProductLines { get; set; }
        public virtual ICollection<ProductUsage> ProductUsages { get; set; }
        public virtual ICollection<ProjectCharge> ProjectCharges { get; set; }
        public virtual ICollection<ProjectMapQtyRange> ProjectMapQtyRanges { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<ProjectType> ProjectTypes { get; set; }
        public virtual ICollection<Prospect> Prospects { get; set; }
        public virtual ICollection<ProductType> ProductTypes { get; set; }
        public virtual ICollection<QuoteType> QuoteTypes { get; set; }
        public virtual ICollection<Source> Sources { get; set; }
        public virtual ICollection<StandardClaus> StandardClauses { get; set; }
        public virtual ICollection<Surcharge> Surcharges { get; set; }
        public virtual ICollection<Terms_Discount> Terms_Discount { get; set; }
        public virtual ICollection<TQS_bbty> TQS_bbty { get; set; }
        public virtual ICollection<TQS_encd> TQS_encd { get; set; }
        public virtual ICollection<TQS_envr> TQS_envr { get; set; }
        public virtual ICollection<TQS_mtac> TQS_mtac { get; set; }
        public virtual ICollection<TQS_mtbt> TQS_mtbt { get; set; }
        public virtual ICollection<TQS_mtlc> TQS_mtlc { get; set; }
        public virtual ICollection<TQS_mtlp> TQS_mtlp { get; set; }
        public virtual ICollection<TQS_mxca> TQS_mxca { get; set; }
        public virtual ICollection<TQS_mxcc> TQS_mxcc { get; set; }
        public virtual ICollection<TQS_prjp> TQS_prjp { get; set; }
        public virtual ICollection<TQS_work> TQS_work { get; set; }
        public virtual ICollection<Unit_Of_Measure> Unit_Of_Measure1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<VehicleType> VehicleTypes { get; set; }
        public virtual ICollection<ZoneCode> ZoneCodes { get; set; }
        public virtual ICollection<BI_Exports> BI_Exports { get; set; }
    }
}
