//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumersprojectimport
    {
        public string Plant { get; set; }
        public string Project_Name { get; set; }
        public string Address___City { get; set; }
        public string Status { get; set; }
        public string Account_Name { get; set; }
        public string Date_Job_Created { get; set; }
        public string Volume { get; set; }
        public string Type { get; set; }
        public string Segment { get; set; }
        public string Bid_Date { get; set; }
        public string Sales_Person { get; set; }
        public string Source { get; set; }
        public string Private { get; set; }
        public string CompanyId { get; set; }
        public string C_Balance_Volume_to_Forecast_ { get; set; }
        public string C14_Jan { get; set; }
        public string C14_Feb { get; set; }
        public string C14_Mar { get; set; }
        public string C14_Apr { get; set; }
        public string C14_May { get; set; }
        public string C14_Jun { get; set; }
        public string C14_Jul { get; set; }
        public string C14_Aug { get; set; }
        public string C14_Sep { get; set; }
        public string C14_Oct { get; set; }
        public string C14_Nov { get; set; }
        public string C14_Dec { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    }
}
