//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.ContactNotes = new HashSet<ContactNote>();
            this.CustomerEvents = new HashSet<CustomerEvent>();
            this.Quotes = new HashSet<Quote>();
            this.SalespersonContacts = new HashSet<SalespersonContact>();
        }
    
        public int ContactID { get; set; }
        public Nullable<bool> Private { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public int ProspectID { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public string FullName { get; set; }
        public string Title { get; set; }
        public string StartingYearatCompany { get; set; }
        public string Department { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Salutation { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Inserted { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Country { get; set; }
        public System.DateTime MsModificationDate { get; set; }
        public bool Inactive { get; set; }
    
        public virtual Prospect Prospect { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ContactNote> ContactNotes { get; set; }
        public virtual ICollection<CustomerEvent> CustomerEvents { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<SalespersonContact> SalespersonContacts { get; set; }
    }
}
