//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEvent
    {
        public int CustomerEventID { get; set; }
        public Nullable<bool> Private { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public int EventTypeID { get; set; }
        public System.DateTime EventStartDate { get; set; }
        public Nullable<System.DateTime> EventEndDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> ContactID { get; set; }
        public int UserID { get; set; }
        public int EventFrequencyID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> MasterEventID { get; set; }
        public int EventStatusID { get; set; }
        public string Subject { get; set; }
        public Nullable<int> ProspectID { get; set; }
        public Nullable<System.DateTime> RecurrenceEndDate { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual CustomerEventType CustomerEventType { get; set; }
        public virtual EventFrequency EventFrequency { get; set; }
        public virtual EventStatu EventStatu { get; set; }
        public virtual Project Project { get; set; }
        public virtual Prospect Prospect { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
