//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_ID { get; set; }
        public Nullable<int> Employee_Type_ID { get; set; }
        public Nullable<int> Home_Plant_ID { get; set; }
        public string Employee_Number { get; set; }
        public System.DateTime Hire_Date { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Complete_Name { get; set; }
        public string Addrees_1 { get; set; }
        public string Address_2 { get; set; }
        public string Address_3 { get; set; }
        public string Address_4 { get; set; }
        public string Address_5 { get; set; }
        public string Address_6 { get; set; }
        public string Address_7 { get; set; }
        public string Home_Phone { get; set; }
        public string Business_Phone { get; set; }
        public string Cell_Phone { get; set; }
        public string Pager { get; set; }
        public string Email_Address { get; set; }
        public string Social_Security_Number { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public Nullable<decimal> Pay_Rate { get; set; }
        public bool Inactive_Flag { get; set; }
        public Nullable<int> User_Profile_ID { get; set; }
        public Nullable<bool> Punch_Out_Flag { get; set; }
        public string Ticket_Writer_Format_File_Concrete { get; set; }
        public string Ticket_Writer_Format_File_Aggregate { get; set; }
        public string Ticket_Writer_Format_File_Block { get; set; }
        public int CompanyID { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
