//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventFrequency
    {
        public EventFrequency()
        {
            this.CustomerEvents = new HashSet<CustomerEvent>();
        }
    
        public int EventFrequencyID { get; set; }
        public int CompanyID { get; set; }
        public string EventFrequency1 { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<CustomerEvent> CustomerEvents { get; set; }
    }
}
