//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTerm
    {
        public PaymentTerm()
        {
            this.Prospects = new HashSet<Prospect>();
        }
    
        public int Terms_Discount_ID { get; set; }
        public int CompanyID { get; set; }
        public string Description { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Prospect> Prospects { get; set; }
    }
}
