//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantProduct
    {
        public int PlantProductID { get; set; }
        public int PlantID { get; set; }
        public int ProductID { get; set; }
        public string Description { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual Product Product { get; set; }
    }
}
