//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PourSchedule
    {
        public PourSchedule()
        {
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
        }
    
        public int PourID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<bool> defaultschedule { get; set; }
        public Nullable<int> ProjectProductID { get; set; }
        public string PourScheduleName { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual ProjectProduct ProjectProduct { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
    }
}
