//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.AdditionalProducts = new HashSet<AdditionalProduct>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.PlantProductPrices = new HashSet<PlantProductPrice>();
            this.PlantProducts = new HashSet<PlantProduct>();
            this.ProjectProducts = new HashSet<ProjectProduct>();
            this.ProspectQuantities = new HashSet<ProspectQuantity>();
            this.StandardClauses = new HashSet<StandardClaus>();
            this.TemplatedProducts = new HashSet<TemplatedProduct>();
            this.ValueAdds = new HashSet<ValueAdd>();
        }
    
        public int ProductID { get; set; }
        public int CompanyID { get; set; }
        public string ProductName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> AU_ID { get; set; }
        public Nullable<int> UnitOfMeasureID { get; set; }
        public int ProductTypeID { get; set; }
        public string ConnectionCode { get; set; }
        public string ITEM_CAT { get; set; }
        public string Product_Code { get; set; }
        public Nullable<System.DateTime> Inserted { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string extProduct_Code { get; set; }
        public bool IsSellable { get; set; }
        public System.DateTime MsModificationDate { get; set; }
        public string ProductShortName { get; set; }
    
        public virtual ICollection<AdditionalProduct> AdditionalProducts { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<PlantProductPrice> PlantProductPrices { get; set; }
        public virtual ICollection<PlantProduct> PlantProducts { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Unit_Of_Measure Unit_Of_Measure { get; set; }
        public virtual ICollection<ProjectProduct> ProjectProducts { get; set; }
        public virtual ICollection<ProspectQuantity> ProspectQuantities { get; set; }
        public virtual ICollection<StandardClaus> StandardClauses { get; set; }
        public virtual ICollection<TemplatedProduct> TemplatedProducts { get; set; }
        public virtual ICollection<ValueAdd> ValueAdds { get; set; }
    }
}
