//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public ProductType()
        {
            this.Products = new HashSet<Product>();
            this.ProjectProducts = new HashSet<ProjectProduct>();
            this.TemplatedProducts = new HashSet<TemplatedProduct>();
            this.TemplatedProductTypes = new HashSet<TemplatedProductType>();
            this.ValueAdds = new HashSet<ValueAdd>();
        }
    
        public int ProductTypeID { get; set; }
        public int CompanyID { get; set; }
        public string ProductTypeName { get; set; }
        public int ProductLineID { get; set; }
        public decimal ListPrice { get; set; }
        public Nullable<int> UOMID { get; set; }
        public bool Inactive { get; set; }
        public string ProductTypeCode { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ProductLine ProductLine { get; set; }
        public virtual Unit_Of_Measure Unit_Of_Measure { get; set; }
        public virtual ICollection<ProjectProduct> ProjectProducts { get; set; }
        public virtual ICollection<TemplatedProduct> TemplatedProducts { get; set; }
        public virtual ICollection<TemplatedProductType> TemplatedProductTypes { get; set; }
        public virtual ICollection<ValueAdd> ValueAdds { get; set; }
    }
}
