//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLine
    {
        public ProductLine()
        {
            this.Plants = new HashSet<Plant>();
            this.ProductLineLineOfBusinesses = new HashSet<ProductLineLineOfBusiness>();
            this.ProductUsages = new HashSet<ProductUsage>();
            this.ProjectBidderCharges = new HashSet<ProjectBidderCharge>();
            this.ProjectProducts = new HashSet<ProjectProduct>();
            this.ProductTypes = new HashSet<ProductType>();
            this.StandardClauses = new HashSet<StandardClaus>();
            this.TemplatedProducts = new HashSet<TemplatedProduct>();
            this.ValueAdds = new HashSet<ValueAdd>();
        }
    
        public int ProductLineID { get; set; }
        public int CompanyID { get; set; }
        public string ProductLineCode { get; set; }
        public string ProductLineName { get; set; }
        public bool Active { get; set; }
        public string extProductLineCode { get; set; }
        public int LineOfBusinessID { get; set; }
        public System.DateTime MsModificationDate { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Plant> Plants { get; set; }
        public virtual ICollection<ProductLineLineOfBusiness> ProductLineLineOfBusinesses { get; set; }
        public virtual ICollection<ProductUsage> ProductUsages { get; set; }
        public virtual ICollection<ProjectBidderCharge> ProjectBidderCharges { get; set; }
        public virtual ICollection<ProjectProduct> ProjectProducts { get; set; }
        public virtual ICollection<ProductType> ProductTypes { get; set; }
        public virtual ICollection<StandardClaus> StandardClauses { get; set; }
        public virtual ICollection<TemplatedProduct> TemplatedProducts { get; set; }
        public virtual ICollection<ValueAdd> ValueAdds { get; set; }
    }
}
