//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectBidderStatus
    {
        public ProjectBidderStatus()
        {
            this.ProjectBidders = new HashSet<ProjectBidder>();
        }
    
        public int ProjectBidderStatusID { get; set; }
        public string StatusName { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual ICollection<ProjectBidder> ProjectBidders { get; set; }
    }
}
