//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectChargeType
    {
        public ProjectChargeType()
        {
            this.ProjectCharges = new HashSet<ProjectCharge>();
        }
    
        public int ChargeTypeID { get; set; }
        public string ChargeTypeName { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual ICollection<ProjectCharge> ProjectCharges { get; set; }
    }
}
