//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectHistorySummary
    {
        public int ProjectHistorySummaryID { get; set; }
        public Nullable<int> ProspectID { get; set; }
        public string PROJ_CODE { get; set; }
        public string PROJ_NAME { get; set; }
        public Nullable<System.DateTime> SETUP_DATE { get; set; }
        public Nullable<System.DateTime> EXPIR_DATE { get; set; }
        public Nullable<int> Orders { get; set; }
        public Nullable<int> Tickets { get; set; }
        public Nullable<decimal> Yards { get; set; }
        public Nullable<decimal> AvgPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Prospect Prospect { get; set; }
    }
}
