//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectNote
    {
        public int ProspectNoteID { get; set; }
        public int ProspectID { get; set; }
        public string Note { get; set; }
        public System.DateTime Inserted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Subject { get; set; }
        public string Source { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Prospect Prospect { get; set; }
        public virtual User User { get; set; }
    }
}
