//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectRegion
    {
        public int ProspectRegionID { get; set; }
        public int ProspectID { get; set; }
        public int PlantID { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Prospect Prospect { get; set; }
    }
}
