//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospect
    {
        public Prospect()
        {
            this.Contacts = new HashSet<Contact>();
            this.CustomerEvents = new HashSet<CustomerEvent>();
            this.Orders = new HashSet<Order>();
            this.ProjectBidders = new HashSet<ProjectBidder>();
            this.ProjectHistorySummaries = new HashSet<ProjectHistorySummary>();
            this.ProspectNotes = new HashSet<ProspectNote>();
            this.ProspectQuantities = new HashSet<ProspectQuantity>();
            this.ProspectRegions = new HashSet<ProspectRegion>();
        }
    
        public int ProspectID { get; set; }
        public Nullable<bool> Private { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public int CompanyID { get; set; }
        public string ProspectName { get; set; }
        public System.DateTime Inserted { get; set; }
        public System.DateTime Modified { get; set; }
        public string ProspectCode { get; set; }
        public string ConnectionCode { get; set; }
        public string LocalCustNumber { get; set; }
        public string LocalCustName { get; set; }
        public bool IsCustomer { get; set; }
        public Nullable<int> Credit_Status_ID { get; set; }
        public string CustomerStatus { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> MaterialMargin { get; set; }
        public Nullable<int> JobCount { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> HighestBalance { get; set; }
        public Nullable<decimal> AvgInvoiceAmt { get; set; }
        public Nullable<int> AvgDaysToPay { get; set; }
        public Nullable<int> AvgDaysPastDue { get; set; }
        public Nullable<decimal> TotalDue { get; set; }
        public Nullable<decimal> ZeroTo30Days { get; set; }
        public Nullable<decimal> ThirtyOneTo60Days { get; set; }
        public Nullable<decimal> SixtyOneTo90Days { get; set; }
        public Nullable<decimal> NinetyOneTo120Days { get; set; }
        public Nullable<decimal> Over120Days { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public string StatementFrequency { get; set; }
        public Nullable<decimal> FinanceRate { get; set; }
        public Nullable<int> PaymentTermsID { get; set; }
        public string SalesmanCode { get; set; }
        public string Fax { get; set; }
        public string WebSite { get; set; }
        public Nullable<decimal> AvgRevenue { get; set; }
        public string NumberofEmployees { get; set; }
        public string CompanyOriginDate { get; set; }
        public Nullable<int> BusinessTypeID { get; set; }
        public string Notes { get; set; }
        public string Country { get; set; }
        public Nullable<bool> PORequired { get; set; }
        public System.DateTime MsModificationDate { get; set; }
        public string Address3 { get; set; }
        public string AccountCategoryDescr { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<CustomerEvent> CustomerEvents { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual ICollection<ProjectBidder> ProjectBidders { get; set; }
        public virtual ICollection<ProjectHistorySummary> ProjectHistorySummaries { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual ICollection<ProspectNote> ProspectNotes { get; set; }
        public virtual ICollection<ProspectQuantity> ProspectQuantities { get; set; }
        public virtual ICollection<ProspectRegion> ProspectRegions { get; set; }
        public virtual User User { get; set; }
    }
}
