//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteType
    {
        public QuoteType()
        {
            this.Companies = new HashSet<Company>();
            this.Quotes = new HashSet<Quote>();
        }
    
        public int QuoteTypeID { get; set; }
        public int CompanyID { get; set; }
        public string QuoteTypeName { get; set; }
        public string Section1 { get; set; }
        public string Section2 { get; set; }
        public string Section3 { get; set; }
        public string ImageLocation { get; set; }
        public bool Inactive { get; set; }
        public Nullable<bool> UseForImport { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
