//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteDetail
    {
        public int QuoteDetailID { get; set; }
        public int QuoteID { get; set; }
        public int ProjectProductID { get; set; }
        public decimal Price { get; set; }
        public decimal Qty { get; set; }
        public decimal Freight { get; set; }
        public decimal FreightPay { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<decimal> CustomerPrice { get; set; }
        public System.DateTime MsModificationDate { get; set; }
        public string Note { get; set; }
    
        public virtual ProjectProduct ProjectProduct { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
