//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleItem
    {
        public int ScheduleItemID { get; set; }
        public int ScheduleID { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime Month { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
