//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        public int ScheduleID { get; set; }
        public int PourScheduleID { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> monthYds { get; set; }
        public Nullable<int> monthPercent { get; set; }
        public int Month { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual PourSchedule PourSchedule { get; set; }
    }
}
