//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceSystem
    {
        public SourceSystem()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public int SourceSystemID { get; set; }
        public string SystemName { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
    }
}
