//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surcharge
    {
        public Surcharge()
        {
            this.QuoteSurcharges = new HashSet<QuoteSurcharge>();
        }
    
        public int SurchargeID { get; set; }
        public int CompanyID { get; set; }
        public string SurchargeName { get; set; }
        public decimal Rate { get; set; }
        public int UOMID { get; set; }
        public bool Active { get; set; }
        public bool QuoteDefault { get; set; }
        public bool QuoteSelectable { get; set; }
        public Nullable<int> PlantID { get; set; }
        public string LocalSurchargeID { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ICollection<QuoteSurcharge> QuoteSurcharges { get; set; }
        public virtual Unit_Of_Measure Unit_Of_Measure { get; set; }
    }
}
