//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatedProductType
    {
        public int TemplatedProductTypeID { get; set; }
        public int ProductTemplateID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IncludeQtyInForecast { get; set; }
        public Nullable<int> ProductUsageID { get; set; }
        public string Note { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual ProductTemplate ProductTemplate { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual ProductUsage ProductUsage { get; set; }
    }
}
