//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCalendar
    {
        public int CalendarDateId { get; set; }
        public System.DateTime CalendarDate { get; set; }
        public Nullable<System.DateTime> DayEnd { get; set; }
        public System.DateTime FirstDayOfMonth { get; set; }
        public System.DateTime LastDayOfMonth { get; set; }
        public Nullable<System.DateTime> MonthEnd { get; set; }
        public System.DateTime FirstDayOfQtr { get; set; }
        public System.DateTime LastDayOfQtr { get; set; }
        public Nullable<System.DateTime> QuarterEnd { get; set; }
        public byte Month { get; set; }
        public byte Day { get; set; }
        public short Year { get; set; }
        public byte DayOfWeek { get; set; }
        public byte DayOfQtr { get; set; }
        public short DayOfYear { get; set; }
        public byte WeekOfYear { get; set; }
        public byte Quarter { get; set; }
        public string LastDayOfMonthFlag { get; set; }
        public string FirstDayOfQtrFlag { get; set; }
        public string LastDayOfQtrFlag { get; set; }
        public string MonthAbbrev { get; set; }
        public string DayAbbrev { get; set; }
        public string MonthName { get; set; }
        public string DayName { get; set; }
        public bool CompanyHoliday { get; set; }
        public bool BusinessDay { get; set; }
        public string MonthYearAbbrev { get; set; }
        public string QtrYearAbbrev { get; set; }
    }
}
