//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQS_cnfc
    {
        public int CompanyID { get; set; }
        public decimal structure_segment_type { get; set; }
        public decimal structure_segment_number { get; set; }
        public string structure_segment_mask { get; set; }
        public string structure_segment_id { get; set; }
        public Nullable<decimal> structure_segment_length { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string u_version { get; set; }
    }
}
