//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQS_mtac
    {
        public int CompanyID { get; set; }
        public string matl_class_id { get; set; }
        public string matl_class_type { get; set; }
        public decimal agg_size { get; set; }
        public Nullable<decimal> dflt_cem_cont { get; set; }
        public Nullable<decimal> min_cem_cont { get; set; }
        public Nullable<decimal> max_cem_cont { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string u_version { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
