//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQS_mtlc
    {
        public int CompanyID { get; set; }
        public string matl_class_id { get; set; }
        public string matl_class_type { get; set; }
        public string descr { get; set; }
        public string short_descr { get; set; }
        public string base_matl_class_id { get; set; }
        public string item_code_segment_id { get; set; }
        public Nullable<decimal> min_replacement_pct { get; set; }
        public Nullable<decimal> max_replacement_pct { get; set; }
        public string cem_price_chart { get; set; }
        public Nullable<decimal> strgth_modifier { get; set; }
        public Nullable<decimal> dflt_order_qty { get; set; }
        public string dflt_order_qty_uom { get; set; }
        public string admix_water_adj_type { get; set; }
        public string item_cat { get; set; }
        public Nullable<bool> batch_book_mix_flag { get; set; }
        public Nullable<bool> strgth_allowed_flag { get; set; }
        public Nullable<decimal> dflt_strgth { get; set; }
        public Nullable<decimal> min_strgth { get; set; }
        public Nullable<decimal> max_strgth { get; set; }
        public Nullable<bool> water_cem_ratio_allowed_flag { get; set; }
        public Nullable<decimal> dflt_water_cem_ratio { get; set; }
        public Nullable<decimal> min_water_cem_ratio { get; set; }
        public Nullable<decimal> max_water_cem_ratio { get; set; }
        public Nullable<bool> cem_cont_allowed_flag { get; set; }
        public Nullable<decimal> dflt_cem_cont { get; set; }
        public Nullable<decimal> min_cem_cont { get; set; }
        public Nullable<decimal> max_cem_cont { get; set; }
        public Nullable<decimal> max_agg_size { get; set; }
        public string notify_msg { get; set; }
        public Nullable<bool> enviro_class_allowed_flag { get; set; }
        public string dflt_enviro_class_code { get; set; }
        public Nullable<bool> consistence_allowed_flag { get; set; }
        public string dflt_consistence_code { get; set; }
        public Nullable<decimal> min_workability_value { get; set; }
        public Nullable<decimal> max_workability_value { get; set; }
        public string terminal_class { get; set; }
        public string cart_cat { get; set; }
        public string print_control { get; set; }
        public Nullable<decimal> mix_design_min_agg_size { get; set; }
        public Nullable<decimal> mix_design_max_agg_size { get; set; }
        public Nullable<decimal> wet_batch_time { get; set; }
        public Nullable<decimal> dry_batch_time { get; set; }
        public Nullable<bool> water_chute_wash_flag { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string u_version { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
