//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit_Of_Measure
    {
        public Unit_Of_Measure()
        {
            this.Companies = new HashSet<Company>();
            this.Products = new HashSet<Product>();
            this.ProductTypes = new HashSet<ProductType>();
            this.ProjectProducts = new HashSet<ProjectProduct>();
            this.Surcharges = new HashSet<Surcharge>();
            this.TemplatedProducts = new HashSet<TemplatedProduct>();
        }
    
        public int Unit_Of_Measure_ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Imperial_Description { get; set; }
        public string Metric_Description { get; set; }
        public Nullable<decimal> Imperial_To_Metric_Conv_Factor { get; set; }
        public Nullable<int> Conversion_Factor_Type_ID { get; set; }
        public Nullable<decimal> Conversion_Factor_Value { get; set; }
        public string ConnectionCode { get; set; }
        public string UOM { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ProductType> ProductTypes { get; set; }
        public virtual ICollection<ProjectProduct> ProjectProducts { get; set; }
        public virtual ICollection<Surcharge> Surcharges { get; set; }
        public virtual ICollection<TemplatedProduct> TemplatedProducts { get; set; }
    }
}
