using System;
using OracleCloud.DTOs;

namespace OracleCloud.Interfaces {
    public interface IOracleRepository {
        void Dispose();
        int CompanyId { get; set; }
        object GetCompanies(Company c, int runId);
        object GetCompanyBidStatuses(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        Company GetCompanyInfo(int companyId);
        object GetCompanyOrderStatuses(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetCompanyProjectProductStatuses(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetCompanyProjectStatuses(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetCompanyQuoteStatuses(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetCompanyUsers(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetCompetitorPlants(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetCompetitors(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetContactNotes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetContacts(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetCreditStatuses(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetCustomerEvents(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetCustomerEventTypes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetCustomerTypes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetDeletedItems(int id, DateTime startDate, DateTime endDate, int runId);
        object GetDeviationTypes(DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetDivisions(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetEventFrequency(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetEventStatuses(DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetLinesOfBusiness(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetLogins(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetLostReasons(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetManagersSalesmen(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetOrderDetails(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetOrders(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetPaymentTerms(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetPlantLinesOfBusiness(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetPlantProductPrices(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        int GetNextRunId();
        object GetPlants(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProductLines(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProducts(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProductTemplates(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProductTypes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProductUsage(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectBidderCharges(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectBidderNotes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectBidderProducts(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectBidders(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectBidderStatuses(DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectCharges(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectChargeTypes(DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectDistances(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectMapQtyRanges(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectNotes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectProducts(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjects(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProjectTypes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProspectNotes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetProspects(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetQuoteDetails(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetQuotes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetQuoteSections(DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetQuoteStandardClauses(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetQuoteStatuses(DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetQuoteSurcharges(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetQuoteTypes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetRoles(DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetSalespersonContacts(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetSalesPersonRegions(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetScheduleItems(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetSchedules(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetSources(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetSourceSystem(SourceSystem ss);
        object GetStandardClauses(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetStatuses(DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetSurcharges(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetTemplatedProducts(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetTermsDiscount(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetUnitsOfMeasure(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetUserRoles(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetUsers(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetVehicleTypes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        object GetZoneCodes(int id, DateTime startDate, DateTime endDate, bool limitRecords, int runId);
        void WriteResults(ReturnDto obj, int runId);
    }
}