//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalProduct
    {
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string CostPerUnit { get; set; }
        public bool Active { get; set; }
        public int ID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int CompanyID { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Division Division { get; set; }
        public virtual Product Product { get; set; }
    }
}
