//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetedYard
    {
        public int BudgetedYardsID { get; set; }
        public int UserID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int BudgetedYards { get; set; }
        public int BudgetedRevenue { get; set; }
        public Nullable<int> ValueAddID { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ValueAdd ValueAdd { get; set; }
    }
}
