//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitorPlant
    {
        public CompetitorPlant()
        {
            this.ProjectProducts = new HashSet<ProjectProduct>();
            this.Projects = new HashSet<Project>();
        }
    
        public int CompetitorPlantID { get; set; }
        public int CompetitorID { get; set; }
        public string PlantName { get; set; }
        public System.DateTime Inserted { get; set; }
        public System.DateTime Modified { get; set; }
        public bool Inactive_Flag { get; set; }
        public Nullable<decimal> PlantCost { get; set; }
        public Nullable<decimal> DeliveryCost { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<decimal> SGACost { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public int DivisionID { get; set; }
        public int LineOfBusinessID { get; set; }
        public string Country { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Competitor Competitor { get; set; }
        public virtual Division Division { get; set; }
        public virtual LinesOfBusiness LinesOfBusiness { get; set; }
        public virtual ICollection<ProjectProduct> ProjectProducts { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
