//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedItem
    {
        public int DeletedItemID { get; set; }
        public int CompanyID { get; set; }
        public int KeyID { get; set; }
        public string TableName { get; set; }
        public System.DateTime DateDeleted { get; set; }
    }
}
