//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinesOfBusiness
    {
        public LinesOfBusiness()
        {
            this.CompetitorPlants = new HashSet<CompetitorPlant>();
            this.PlantLinesOfBusinesses = new HashSet<PlantLinesOfBusiness>();
            this.ProductLineLineOfBusinesses = new HashSet<ProductLineLineOfBusiness>();
            this.ProjectProducts = new HashSet<ProjectProduct>();
            this.TemplatedProducts = new HashSet<TemplatedProduct>();
        }
    
        public int LineOfBusinessID { get; set; }
        public string Name { get; set; }
        public int CompanyID { get; set; }
        public string LineOfBusinessCode { get; set; }
        public System.DateTime MsModificationDate { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<CompetitorPlant> CompetitorPlants { get; set; }
        public virtual ICollection<PlantLinesOfBusiness> PlantLinesOfBusinesses { get; set; }
        public virtual ICollection<ProductLineLineOfBusiness> ProductLineLineOfBusinesses { get; set; }
        public virtual ICollection<ProjectProduct> ProjectProducts { get; set; }
        public virtual ICollection<TemplatedProduct> TemplatedProducts { get; set; }
    }
}
