//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductUsage
    {
        public ProductUsage()
        {
            this.ProjectProducts = new HashSet<ProjectProduct>();
            this.StandardClauses = new HashSet<StandardClaus>();
            this.TemplatedProducts = new HashSet<TemplatedProduct>();
            this.TemplatedProductTypes = new HashSet<TemplatedProductType>();
        }
    
        public int ProductUsageID { get; set; }
        public int CompanyID { get; set; }
        public string ProductUsageName { get; set; }
        public Nullable<int> ProductLineID { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ProductLine ProductLine { get; set; }
        public virtual ICollection<ProjectProduct> ProjectProducts { get; set; }
        public virtual ICollection<StandardClaus> StandardClauses { get; set; }
        public virtual ICollection<TemplatedProduct> TemplatedProducts { get; set; }
        public virtual ICollection<TemplatedProductType> TemplatedProductTypes { get; set; }
    }
}
