//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectType
    {
        public ProjectType()
        {
            this.Projects = new HashSet<Project>();
            this.Prospects = new HashSet<Prospect>();
        }
    
        public int ProjectTypeID { get; set; }
        public int CompanyID { get; set; }
        public string ConnectionCode { get; set; }
        public string SANL_Code { get; set; }
        public string ProjectTypeName { get; set; }
        public string ShortName { get; set; }
        public System.DateTime Inserted { get; set; }
        public System.DateTime Modified { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Prospect> Prospects { get; set; }
    }
}
