//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCharge
    {
        public ProjectCharge()
        {
            this.ProjectBidderCharges = new HashSet<ProjectBidderCharge>();
            this.ProjectBidders = new HashSet<ProjectBidder>();
            this.ProjectBidders1 = new HashSet<ProjectBidder>();
            this.ProjectBidders2 = new HashSet<ProjectBidder>();
            this.ProjectBidders3 = new HashSet<ProjectBidder>();
        }
    
        public int ChargeID { get; set; }
        public string ChargeName { get; set; }
        public int ChargeType { get; set; }
        public string ChargeCode { get; set; }
        public int CompanyID { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<ProjectBidderCharge> ProjectBidderCharges { get; set; }
        public virtual ICollection<ProjectBidder> ProjectBidders { get; set; }
        public virtual ICollection<ProjectBidder> ProjectBidders1 { get; set; }
        public virtual ICollection<ProjectBidder> ProjectBidders2 { get; set; }
        public virtual ICollection<ProjectBidder> ProjectBidders3 { get; set; }
        public virtual ProjectChargeType ProjectChargeType { get; set; }
    }
}
