//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteStatus
    {
        public QuoteStatus()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public int QuoteStatusID { get; set; }
        public string QuoteStatusName { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime MsModificationDate { get; set; }
    
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
