//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQS_encd
    {
        public int CompanyID { get; set; }
        public string enviro_class_code { get; set; }
        public string cem_matl_class_id { get; set; }
        public decimal agg_size { get; set; }
        public Nullable<decimal> min_cem_cont { get; set; }
        public Nullable<decimal> max_water_cem_ratio { get; set; }
        public string printable_field { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string u_version { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
