//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQS_prjp
    {
        public int CompanyID { get; set; }
        public string cust_code { get; set; }
        public string proj_code { get; set; }
        public decimal intrnl_line_num { get; set; }
        public Nullable<decimal> sort_line_num { get; set; }
        public string prod_code { get; set; }
        public string batch_code { get; set; }
        public string prod_descr { get; set; }
        public Nullable<decimal> est_qty { get; set; }
        public string rm_slump { get; set; }
        public string rm_slump_uom { get; set; }
        public string usage_code { get; set; }
        public string short_prod_descr { get; set; }
        public string price_uom { get; set; }
        public Nullable<decimal> price { get; set; }
        public string price_ext_code { get; set; }
        public string price_plant_code { get; set; }
        public Nullable<System.DateTime> effect_date { get; set; }
        public Nullable<decimal> prev_price { get; set; }
        public string prev_price_ext_code { get; set; }
        public Nullable<bool> delv_price_flag { get; set; }
        public Nullable<decimal> dflt_load_qty { get; set; }
        public string order_qty_uom { get; set; }
        public string order_qty_ext_code { get; set; }
        public Nullable<decimal> order_dosage_qty { get; set; }
        public string order_dosage_qty_uom { get; set; }
        public string delv_qty_uom { get; set; }
        public string price_qty_ext_code { get; set; }
        public string tkt_qty_ext_code { get; set; }
        public string mix_type { get; set; }
        public string item_type { get; set; }
        public string quote_code { get; set; }
        public Nullable<bool> allow_price_adjust_flag { get; set; }
        public Nullable<bool> sep_invc_flag { get; set; }
        public Nullable<bool> override_terms_disc_flag { get; set; }
        public string disc_rate_type { get; set; }
        public Nullable<decimal> disc_amt { get; set; }
        public string disc_amt_uom { get; set; }
        public Nullable<decimal> content_up_price { get; set; }
        public Nullable<decimal> content_down_price { get; set; }
        public Nullable<System.DateTime> content_up_price_effect_date { get; set; }
        public Nullable<System.DateTime> content_down_price_effect_date { get; set; }
        public Nullable<decimal> prev_content_up_price { get; set; }
        public Nullable<decimal> prev_content_down_price { get; set; }
        public Nullable<decimal> job_quote_unique_line_num { get; set; }
        public string pour_meth_code { get; set; }
        public string ca_truck_type { get; set; }
        public string cb_truck_type { get; set; }
        public string cc_truck_type { get; set; }
        public string cd_truck_type { get; set; }
        public string quote_rev_num { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string type_price { get; set; }
        public Nullable<decimal> matl_price { get; set; }
        public Nullable<bool> auto_prod_flag { get; set; }
        public Nullable<bool> item_cat_price_flag { get; set; }
        public string auth_user_name { get; set; }
        public string price_status { get; set; }
        public Nullable<decimal> unique_line_num { get; set; }
        public string delv_meth_code { get; set; }
        public Nullable<System.DateTime> sched_date { get; set; }
        public Nullable<System.DateTime> sched_time { get; set; }
        public string ship_plant_code { get; set; }
        public string agg_levy_code { get; set; }
        public Nullable<decimal> agg_levy_rate { get; set; }
        public string certificate { get; set; }
        public string alternative_item { get; set; }
        public Nullable<bool> must_finish_flag { get; set; }
        public string econ_source_priority { get; set; }
        public Nullable<decimal> econ_source_margin { get; set; }
        public Nullable<decimal> econ_source_variance { get; set; }
        public string alternative_item_descr { get; set; }
        public string alternative_item_short_descr { get; set; }
        public string record_origin_code { get; set; }
        public string mix_matl_class_id { get; set; }
        public string admix_class_id { get; set; }
        public string coarse_agg_class_id { get; set; }
        public string cem_class_id { get; set; }
        public string fine_agg_class_id { get; set; }
        public string water_class_id { get; set; }
        public string batch_book_type { get; set; }
        public string consistence_code { get; set; }
        public Nullable<decimal> workability_value { get; set; }
        public string strgth_code { get; set; }
        public Nullable<decimal> strgth_value { get; set; }
        public Nullable<decimal> max_water_cem_ratio { get; set; }
        public Nullable<decimal> min_cem_cont { get; set; }
        public Nullable<decimal> cem_replacement_pct { get; set; }
        public Nullable<decimal> max_agg_size { get; set; }
        public string enviro_class_code { get; set; }
        public Nullable<decimal> chloride_class { get; set; }
        public Nullable<decimal> calc_cem_cont { get; set; }
        public string cem_calc_method { get; set; }
        public Nullable<decimal> mortar_lifetime { get; set; }
        public string mix_cert_status { get; set; }
        public Nullable<decimal> cert_cem_cont { get; set; }
        public Nullable<decimal> original_cost { get; set; }
        public string chrg_cart_code { get; set; }
        public Nullable<decimal> chrg_cart_rate { get; set; }
        public string pay_cart_code { get; set; }
        public Nullable<decimal> tqs_price { get; set; }
        public Nullable<decimal> user_min_cem_cont { get; set; }
        public Nullable<decimal> user_max_water_cem_ratio { get; set; }
        public string es_rsn_code { get; set; }
        public Nullable<decimal> es_selected_tot_std_cost { get; set; }
        public Nullable<decimal> es_most_econ_tot_std_cost { get; set; }
        public string es_most_economical_plant { get; set; }
        public string es_most_economical_alternative { get; set; }
        public string es_user_name { get; set; }
        public string po_restrict_code { get; set; }
        public string po_restrict_warn_code { get; set; }
        public Nullable<System.DateTime> price_expir_date { get; set; }
        public string product_status { get; set; }
        public string price_loc_code { get; set; }
        public string chloride_class_code { get; set; }
        public string chrg_cart_rate_status { get; set; }
        public Nullable<decimal> pay_cart_rate { get; set; }
        public string pay_cart_rate_status { get; set; }
        public Nullable<System.DateTime> item_stat_effect_date { get; set; }
        public Nullable<decimal> prev_matl_price { get; set; }
        public string tech_manager_approved { get; set; }
        public string modf_1 { get; set; }
        public string modf_2 { get; set; }
        public string modf_3 { get; set; }
        public string modf_4 { get; set; }
        public Nullable<bool> restrict_01 { get; set; }
        public Nullable<bool> restrict_02 { get; set; }
        public Nullable<bool> restrict_03 { get; set; }
        public Nullable<bool> restrict_04 { get; set; }
        public Nullable<bool> restrict_05 { get; set; }
        public string exps_cls { get; set; }
        public Nullable<System.DateTime> std_cost_effect_date { get; set; }
        public Nullable<decimal> curr_std_cost { get; set; }
        public Nullable<decimal> prev_std_cost { get; set; }
        public Nullable<decimal> p_value { get; set; }
        public Nullable<decimal> t_curing_time { get; set; }
        public string t_curing_time_uom { get; set; }
        public string concrete_type_code { get; set; }
        public string design_method_1 { get; set; }
        public string design_method_2 { get; set; }
        public Nullable<decimal> min_cemnt_content { get; set; }
        public Nullable<decimal> f_value { get; set; }
        public Nullable<decimal> max_air_pct { get; set; }
        public Nullable<decimal> additional_fly_ash_pct { get; set; }
        public Nullable<decimal> water_content { get; set; }
        public Nullable<decimal> binder_content { get; set; }
        public Nullable<bool> descr_update_flag { get; set; }
        public Nullable<decimal> min_air_pct { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string u_version { get; set; }
        public string ca_sur_codes { get; set; }
        public string cb_sur_codes { get; set; }
        public string cc_sur_codes { get; set; }
        public string cd_sur_codes { get; set; }
        public string ca_sur_rates { get; set; }
        public string cb_sur_rates { get; set; }
        public string cc_sur_rates { get; set; }
        public string cd_sur_rates { get; set; }
        public string ca_sundry_chrg_table_ids { get; set; }
        public string cb_sundry_chrg_table_ids { get; set; }
        public string cc_sundry_chrg_table_ids { get; set; }
        public string cd_sundry_chrg_table_ids { get; set; }
        public string ca_sundry_chrg_sep_invc_flags { get; set; }
        public string cb_sundry_chrg_sep_invc_flags { get; set; }
        public string cc_sundry_chrg_sep_invc_flags { get; set; }
        public string cd_sundry_chrg_sep_invc_flags { get; set; }
        public string ca_sur_dflt_action_codes { get; set; }
        public string cb_sur_dflt_action_codes { get; set; }
        public string cc_sur_dflt_action_codes { get; set; }
        public string cd_sur_dflt_action_codes { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
